# Generated by Django 4.1.1 on 2025-02-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default='Personal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolistapp.category'),
        ),
    ]
